### ISSUE TITLE
type error:

### ISSUE THREAD

**Issue by sreeteja60** [QuickLearner171998/Facial-Expression-Recognition#1]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from camera import VideoCamera
  File "/home/rhyme/Desktop/Project/camera.py", line 6, in <module>
    model = FacialExpressionModel("model.json", "model_weights.h5")
TypeError: object() takes no parameters

**Comment by QuickLearner171998** [comment]
Did you change anything here - https://github.com/QuickLearner171998/Facial-Expression-Recognition/blob/d6e099c71725f3829cb7d6a1b9e6b5e4401b9d29/model.py#L18

Try converting all tabs to spaces.

For your reference - https://stackoverflow.com/questions/23176597/python-object-takes-no-parameters-error/48728948

**Comment by sreeteja60** [comment]
> Did you change anything here -
> 
> https://github.com/QuickLearner171998/Facial-Expression-Recognition/blob/d6e099c71725f3829cb7d6a1b9e6b5e4401b9d29/model.py#L18
> 
> Try converting all tabs to spaces.
> 
> For your reference - https://stackoverflow.com/questions/23176597/python-object-takes-no-parameters-error/48728948

Thank you, Helped me out!!
